import Mathlib.Analysis.InnerProductSpace.Projection.Reflection
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.Algebra.Group.Subgroup.Lattice

/-! Finite real orthogonal transformations are generated by actual hyperplane
reflections. The empty dimension is included. This theorem supplies no physical
implementation by fiat; it supports induction once each reflection is implemented. -/
noncomputable section
open scoped RealInnerProductSpace
open Module
namespace Gaussian.LinearAlgebra
variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
variable [FiniteDimensional ℝ E]

def hyperplaneReflection (v : E) : E ≃ₗᵢ[ℝ] E := (ℝ ∙ v)ᗮ.reflection

def reflectionGroup : Subgroup (E ≃ₗᵢ[ℝ] E) :=
  Subgroup.closure (Set.range (hyperplaneReflection (E := E)))

@[simp] theorem hyperplaneReflection_involution (v : E) (x : E) :
    hyperplaneReflection v (hyperplaneReflection v x) = x :=
  Submodule.reflection_reflection _ x

private theorem mem_reflectionGroup_of_fixes_complement {ι : Type*} [Fintype ι]
    [DecidableEq ι] (b : Basis ι ℝ E) (s : Finset ι) (R : E ≃ₗᵢ[ℝ] E)
    (hfix : ∀ i, i ∉ s → R (b i) = b i) : R ∈ reflectionGroup (E := E) := by
  induction s using Finset.induction_on generalizing R with
  | empty =>
    have he : R = 1 := by
      apply LinearIsometryEquiv.ext
      have hl : R.toLinearEquiv.toLinearMap = LinearMap.id := by
        apply b.ext
        intro i
        exact hfix i (by simp)
      intro x
      exact congrArg (fun f : E →ₗ[ℝ] E => f x) hl
    rw [he]
    exact (reflectionGroup (E := E)).one_mem
  | @insert i s hi ih =>
    let H := hyperplaneReflection (R (b i)-b i)
    let Q := H * R
    have hQi : Q (b i) = b i := by
      exact Submodule.reflection_sub (R.norm_map (b i))
    have hQ : ∀ j, j ∉ s → Q (b j) = b j := by
      intro j hj
      by_cases hji : j = i
      · simpa only [hji] using hQi
      have hjfix := hfix j (by simp [hj,hji])
      have hjorth : ⟪R (b i)-b i,b j⟫ = 0 := by
        rw [inner_sub_left]
        have he : ⟪R (b i),b j⟫ = ⟪b i,b j⟫ := by
          calc
            ⟪R (b i),b j⟫ = ⟪R (b i),R (b j)⟫ := by rw [hjfix]
            _ = ⟪b i,b j⟫ := R.inner_map_map _ _
        rw [he,sub_self]
      change H (R (b j)) = b j
      rw [hjfix]
      apply Submodule.reflection_mem_subspace_eq_self
      exact Submodule.mem_orthogonal_singleton_iff_inner_left.mpr (by simpa only [real_inner_comm] using hjorth)
    have hQmem := ih Q hQ
    have hHmem : H ∈ reflectionGroup (E := E) :=
      Subgroup.subset_closure ⟨R (b i)-b i,rfl⟩
    have he : R = H * Q := by
      ext x
      exact (hyperplaneReflection_involution (R (b i)-b i) (R x)).symm
    rw [he]
    exact (reflectionGroup (E := E)).mul_mem hHmem hQmem

/-- Every finite real orthogonal transformation is generated by hyperplane reflections. -/
theorem orthogonal_mem_reflectionGroup (R : E ≃ₗᵢ[ℝ] E) : R ∈ reflectionGroup (E := E) := by
  classical
  apply mem_reflectionGroup_of_fixes_complement (stdOrthonormalBasis ℝ E).toBasis Finset.univ R
  simp

theorem reflectionGroup_eq_top : reflectionGroup (E := E) = ⊤ := by
  apply top_unique
  intro R _
  exact orthogonal_mem_reflectionGroup R
end Gaussian.LinearAlgebra
