name = "gaussian_minpur_fresh"
version = "0.1.0"
defaultTargets = ["Gaussian"]
moreLeanArgs = ["-j1", "-Dwarn.sorry=true"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "d13f23b723b8a846827a245b89c10fc7d3f11612"

[[require]]
name = "Physlib"
git = "https://github.com/leanprover-community/physlib.git"
rev = "af484f78ee0701290595f8bf892b157b10d64940"

[[lean_lib]]
name = "Gaussian"
globs = ["Gaussian"]
